### PR TITLE
Updated preferred name for Dnipro in latin-script languages.

### PR DESCRIPTION
**Pull request by andreibalaban**
The name of the city has changed from Dnipropetrovsk to Dnipro -> updated the eng preferred name to reflect that.

Source: https://en.wikipedia.org/wiki/Dnipro

_To comply with the [2015 decommunization law](https://en.wikipedia.org/wiki/Decommunization_in_Ukraine) the city was renamed Dnipro in May 2016, after the river that flows through the city.[[21]](https://en.wikipedia.org/wiki/Dnipro#cite_note-drbvr-21)[[19]](https://en.wikipedia.org/wiki/Dnipro#cite_note-decommupbbcU-19)_

### CODE REVIEW

**Comment by andreibalaban** [comment]
Hello @stepps00 ! Can you please have a look on this?

**Comment by stepps00** [comment]
Hey @andreibalaban - apologies, I didn't see this PR come through at first - thanks for the updates.

We have a `name:{lang}_x_historical` property that we use to house historical names (in this case "Dnipropetrovsk"), so ideally, the property changes would look something like:

```
    "name:spa_x_preferred":[
        "Dnipro"
    ],
    "name:spa_x_historical":[
        "Dnipro"
    ],
```

Would you like to make those adjustments? Either way, I can pull your commit(s) down to validate the changes and merge.

**Comment by andreibalaban** [comment]
@stepps00 Thanks for the feedback, I did the requested changes, hope that everything is ok.

**Comment by stepps00** [comment]
Thanks @andreibalaban - I've opened a new PR with your commits + an additional commit with a few more updates.

**Comment by nvkelso** [comment]
Thanks @andreibalaban! I've just approved #24 which implements your changes here but with some additional changes. I'll close this PR so we don't all get confused. Cheers.

**Pull request closed without merging**
